name: Manual Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy CNAME file
        run: cp public/CNAME dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # or your build output directory

      - name: List build output
        run: |
          echo "Contents of build directory:"
          ls -R .  # or whatever directory Parcel outputs to
